var nome = prompt("Digite o seu nome:")
var idade = prompt("Digite a sua idade:")
var profissao = prompt("Digite a sua profissão:")

console.log()
console.log("--------------")
console.log(nome)
console.log(idade)
console.log(profissao)
console.log("--------------")
console.log("PEQUENA ALTERAÇÃO NA ÚLTIMA LINHA DO CÓDIGO")
